plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Project: ingestion-bench
hostnames:
  - ip-address
compose:
  ansible_host: public_ip_address
  ansible_private_key_file: ../terraform/bench-key-ingestion.pem
keyed_groups:
  - prefix: tag_Role
    key: tags.Role
